### ISSUE TITLE
Broker crashes when acquiring Semaphore on Web while Listener is attached

### ISSUE THREAD

**Issue by paulgessinger** [gessinger-hj/gepard#1]
```bash
node src/Broker.js --web
.bin/gp.listen --name=ALARM
```

then click acquire Semaphore.

Broker terminates with

```bash
/Users/Paul/node_modules/gepard/src/WebSocketEventProxy.js:514
	  	e.body.isSemaphoreOwner = l.isOwner() ;
	  	                            ^
TypeError: Cannot call method 'isOwner' of undefined
    at null._callback (/Users/Paul/node_modules/gepard/src/WebSocketEventProxy.js:514:33)
    at Semaphore._aquireSemaphoreCallback (/Users/Paul/node_modules/gepard/src/Semaphore.js:63:18)
    at Socket.socket_on_data (/Users/Paul/node_modules/gepard/src/Client.js:270:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

**Comment by gessinger-hj** [comment]
The line
<pre>
e.body.isSemaphoreOwner = <b>l.isOwner()</b> ;
</pre>
in the Semaphore-callback must read as:
<pre>
e.body.isSemaphoreOwner = <b>this.isOwner()</b> ;
</pre>
