### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by gessinger-hj** [gessinger-hj/gepard#2]
TypeError: Cannot read property 'replace' of undefined
    at Socket.<anonymous> (node_modules\gepard\src\Client.js:101:45)
    at Socket.g (events.js:196:16)
    at Socket.EventEmitter.emit (events.js:126:20)
    at Object.afterConnect [as oncomplete] (net.js:986:10)

**Comment by gessinger-hj** [comment]
Referenced process.argv[1] is undefined.
This is caused by using Client within a WebKit node_module.
The existens is now tested.
