### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gessinger-hj** [gessinger-hj/gepard#3]
Seit dem Update hab ich Probleme mit den onEnd, onError, onShutdown callBacks.
Wenn ich die auslöse bekomme ich:
TypeError: Cannot convert undefined or null to object
    at onend (node_modules\gepard\index.js:37:44)
    at emitOne (events.js:80:20)
    at emit (events.js:150:7)
    at Socket.socket_on_error (node_modules\gepard\src\Client.js:376:10)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at net.js:432:14
    at process._tickCallback (node.js:375:11)

**Comment by gessinger-hj** [comment]
The _Instances ( of clients ) hash in callbacks for onerror... in index.js has a wrong reference.
Fixed.
