### ISSUE TITLE
gepard.py, [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by gessinger-hj** [gessinger-hj/gepard#4]
[Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "./Emitter.py", line 10, in <module>
    client.close()
  File "/local/data/Projects/gepard/python/xmp/../gepard.py", line 657, in close
    self._NQ_semaphoreEvents.clear()
AttributeError: 'NamedQueue' object has no attribute 'clear'

**Comment by gessinger-hj** [comment]
Fixed as of release 1.4.2
